### ISSUE TITLE
Pause Button Bug

### ISSUE THREAD

**Issue by zachmmeyer** [zachmmeyer/AHK-Pomodoro#1]
![image](https://user-images.githubusercontent.com/34407561/110256881-415f7280-7f69-11eb-8435-462929b6f6e3.png)

**Comment by codeknave** [comment]
works fine

**Comment by codeknave** [comment]
Unable to reproduce

**Comment by codeknave** [comment]
Shit, ain't that the quintessential programmer's problem?

**Comment by zachmmeyer** [comment]
Pressing **Stop** while timer is going changes pause text to glitch out for me. Should have stated in initial issue text.

**Comment by zachmmeyer** [comment]
Issue is fixed.
